systemtests: volume-pruning: add debug output

diff --git a/systemtests/tests/volume-pruning/testrunner b/systemtests/tests/volume-pruning/testrunner
--- a/systemtests/tests/volume-pruning/testrunner
+++ b/systemtests/tests/volume-pruning/testrunner
@@ -78,13 +78,14 @@ stop_bareos
 check_two_logs
 
 if ! grep "Purging the following JobIds: 1,2,3,4,5,6" "$tmp"/log1.out; then
-  echo "Pruned jobs don't match expectations." >&2
+  echo "'Purging the following JobIds: 1,2,3,4,5,6' not found in $tmp/log1.out" >&2
+  grep 'Purging the' "$tmp"/log1.out >&2 || :
   estat=1
 fi
 
-if ! grep -F 'Volume "TestVolume001" contains no jobs after pruning.' \
-    $tmp/log2.out; then
-  echo "Pruning message is wrong." >&2
+if ! grep -F 'Volume "TestVolume001" contains no jobs after pruning.' $tmp/log2.out; then
+  echo "'Volume \"TestVolume001\" contains no jobs after pruning.' not found in $tmp/log2.out" >&2
+  grep 'Volume.*contains no jobs after pruning.' $tmp/log2.out >&2 || :
   estat=1
 fi
 
