test

diff --git a/core/scripts/bareos-ctl-funcs b/core/scripts/bareos-ctl-funcs
--- a/core/scripts/bareos-ctl-funcs
+++ b/core/scripts/bareos-ctl-funcs
@@ -86,16 +86,24 @@ killproc() {
                fi
             fi
          fi
-         ${PS} -p "$pid" >/dev/null 2>&1
-         RC=$?
-         [ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
+         if ${PS} -p "$pid" >/dev/null 2>&1; then
+            success "$base shutdown"
+         else
+            failure "$base shutdown"
+         fi
+         #RC=$?
+         #[ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
          #    RC=$((! $RC))
          # use specified level only
       else
          if ${PS} -p "$pid" >/dev/null 2>&1; then
-            kill $killlevel $pid 2>/dev/null
-            RC=$?
-            [ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
+            if kill $killlevel $pid 2>/dev/null; then
+                success "$base shutdown"
+            else
+                failure "$base shutdown"
+            fi
+            #RC=$?
+            #[ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
          fi
       fi
    else
@@ -180,10 +188,12 @@ status() {
 }
 
 success() {
+   echo "${1:-} succeeded"
    return 0
 }
 
 failure() {
+   echo "FAILED to ${1:-}"
    rc=$?
    return $rc
 }
